2019-08-12 17:53:14,533 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 16:02:59,316 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 16:15:42,427 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 16:16:28,654 - router - INFO - Get all to-dos incomming request
2019-08-13 16:16:28,654 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 8, in get_todos
    repository = Repository()
  File "/home/user/python-training/python_app/repository.py", line 12, in __init__
    self.engine = create_engine(sqlite3.connect('test.db'), echo=True)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'sqlite3.Connection' object has no attribute '_instantiate_plugins'
2019-08-13 16:16:28,685 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 16:16:28] "GET / HTTP/1.1" 500 -
2019-08-13 16:18:56,120 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 16:19:20,072 - router - INFO - Get all to-dos incomming request
2019-08-13 16:19:20,099 - python_app.handler - INFO - Finding all to-dos
2019-08-13 16:19:20,099 - python_app.repository - DEBUG - Getting session
2019-08-13 16:19:20,105 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 16:19:20,105 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 11, in get_todos
    with repository as session:
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 16:19:20,117 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 16:19:20] "GET / HTTP/1.1" 500 -
2019-08-13 16:21:13,405 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 16:22:51,287 - router - INFO - Get all to-dos incomming request
2019-08-13 16:22:51,321 - python_app.handler - INFO - Finding all to-dos
2019-08-13 16:22:51,321 - python_app.repository - DEBUG - Getting session
2019-08-13 16:22:51,321 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 16:22:51,322 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 16:22:51,332 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 16:22:51] "GET / HTTP/1.1" 500 -
2019-08-13 16:23:58,282 - router - INFO - Get all to-dos incomming request
2019-08-13 16:23:58,283 - python_app.handler - INFO - Finding all to-dos
2019-08-13 16:23:58,284 - python_app.repository - DEBUG - Getting session
2019-08-13 16:23:58,285 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 16:23:58,285 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-test/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 16:23:58,289 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 16:23:58] "GET / HTTP/1.1" 500 -
2019-08-13 16:28:37,069 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:43:03,068 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:43:07,372 - router - INFO - Get all to-dos incomming request
2019-08-13 17:43:14,364 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:43:16,706 - python_app.repository - DEBUG - Getting session
2019-08-13 17:43:19,926 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 17:43:19,939 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 17:43:20,015 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 17:43:20] "GET / HTTP/1.1" 500 -
2019-08-13 17:45:05,846 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:45:19,177 - router - INFO - Get all to-dos incomming request
2019-08-13 17:45:22,877 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:45:23,652 - python_app.repository - DEBUG - Getting session
2019-08-13 17:45:24,401 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 17:45:24,406 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 17:45:24,470 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 17:45:24] "GET / HTTP/1.1" 500 -
2019-08-13 17:45:38,932 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:45:45,686 - router - INFO - Get all to-dos incomming request
2019-08-13 17:45:58,098 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:46:03,314 - python_app.repository - DEBUG - Getting session
2019-08-13 17:49:24,799 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:49:29,797 - router - INFO - Get all to-dos incomming request
2019-08-13 17:49:29,816 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:49:32,704 - python_app.repository - DEBUG - Getting session
2019-08-13 17:49:33,652 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 17:49:33,661 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 17:49:33,731 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 17:49:33] "GET / HTTP/1.1" 500 -
2019-08-13 17:51:35,661 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:51:40,139 - router - INFO - Get all to-dos incomming request
2019-08-13 17:51:40,158 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:51:42,602 - python_app.repository - DEBUG - Getting session
2019-08-13 17:51:46,172 - python_app.repository - DEBUG - Rollbacking session
2019-08-13 17:51:46,181 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/python_app/handler.py", line 12, in get_todos
    rows = session.query(Todo).all()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1544, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 168, in __init__
    self._set_entities(entities)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 198, in _set_entities
    entity_wrapper(self, ent)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4480, in __init__
    "expected - got '%r'" % (column,)
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'python_app.todo.Todo'>'
2019-08-13 17:51:46,249 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 17:51:46] "GET / HTTP/1.1" 500 -
2019-08-13 17:57:19,670 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-13 17:57:24,611 - router - INFO - Get all to-dos incomming request
2019-08-13 17:57:24,637 - python_app.handler - INFO - Finding all to-dos
2019-08-13 17:57:28,117 - python_app.repository - DEBUG - Getting session
2019-08-13 17:57:28,788 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-13 17:57:28,790 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-13 17:57:28,796 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-13 17:57:28,797 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-13 17:57:28,801 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-13 17:57:28,803 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-13 17:57:28,804 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-13 17:57:28,812 - python_app.repository - DEBUG - Closing session
2019-08-13 17:57:28,814 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-13 17:57:33,272 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-13 17:57:33,332 - werkzeug - INFO - 127.0.0.1 - - [13/Aug/2019 17:57:33] "GET / HTTP/1.1" 500 -
2019-08-14 09:41:07,903 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 09:45:41,311 - router - INFO - Get all to-dos incomming request
2019-08-14 09:45:41,331 - python_app.handler - INFO - Finding all to-dos
2019-08-14 09:46:14,505 - python_app.repository - DEBUG - Getting session
2019-08-14 09:46:16,232 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 09:46:16,234 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 09:46:16,238 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 09:46:16,239 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 09:46:16,245 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 09:46:16,250 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 09:46:16,251 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 09:46:16,255 - python_app.repository - DEBUG - Closing session
2019-08-14 09:46:16,256 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 09:46:27,816 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 09:46:27,895 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 09:46:27] "GET / HTTP/1.1" 500 -
2019-08-14 10:15:58,168 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:16:09,295 - router - INFO - Get all to-dos incomming request
2019-08-14 10:16:09,322 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:16:11,773 - python_app.repository - DEBUG - Getting session
2019-08-14 10:16:11,796 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:16:11,799 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:16:11,802 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:16:11,804 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:16:11,808 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:16:11,812 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:16:11,814 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:16:11,819 - python_app.repository - DEBUG - Closing session
2019-08-14 10:16:11,820 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 10:16:11,824 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 11, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 10:16:11,839 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:16:11] "GET / HTTP/1.1" 500 -
2019-08-14 10:18:43,491 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:18:47,057 - router - INFO - Get all to-dos incomming request
2019-08-14 10:18:47,084 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:18:49,107 - python_app.repository - DEBUG - Getting session
2019-08-14 10:18:49,140 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:18:49,145 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:18:49,153 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:18:49,156 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:18:49,171 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:18:49,185 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:18:49,191 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:18:49,204 - python_app.repository - DEBUG - Closing session
2019-08-14 10:18:49,206 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 10:18:49,215 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask_jsontools/decorators.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/home/user/python-training/router.py", line 13, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 10:18:49,235 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:18:49] "GET / HTTP/1.1" 500 -
2019-08-14 10:19:38,158 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:19:42,322 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:19:48,072 - router - INFO - Get all to-dos incomming request
2019-08-14 10:19:48,098 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:19:49,860 - python_app.repository - DEBUG - Getting session
2019-08-14 10:19:49,915 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:19:49,920 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:19:49,937 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:19:49,943 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:19:49,956 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:19:49,961 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:19:49,964 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:19:49,972 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask_jsontools/decorators.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/home/user/python-training/router.py", line 13, in get_all_todos
    return jsonify(handler.get_todos())
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 10:19:49,990 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:19:49] "GET / HTTP/1.1" 500 -
2019-08-14 10:19:58,697 - router - INFO - Get all to-dos incomming request
2019-08-14 10:19:58,705 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:20:01,327 - python_app.repository - DEBUG - Getting session
2019-08-14 10:20:02,303 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:20:02,306 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:02,315 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:20:02,319 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:02,323 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:20:02,329 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:20:02,334 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:39,874 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:20:43,574 - router - INFO - Get all to-dos incomming request
2019-08-14 10:20:43,600 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:20:45,370 - python_app.repository - DEBUG - Getting session
2019-08-14 10:20:45,391 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:20:45,393 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:45,396 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:20:45,397 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:45,399 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:20:45,402 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:20:45,403 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:20:45,413 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask_jsontools/decorators.py", line 21, in wrapper
    return make_json_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask_jsontools/response.py", line 79, in make_json_response
    return JsonResponse(rv, status, headers)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask_jsontools/response.py", line 29, in __init__
    json.dumps(self._response_data, indent=indent),
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 10:20:45,428 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:20:45] "GET / HTTP/1.1" 500 -
2019-08-14 10:20:58,025 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:20:59,708 - router - INFO - Get all to-dos incomming request
2019-08-14 10:20:59,740 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:21:01,565 - python_app.repository - DEBUG - Getting session
2019-08-14 10:21:01,583 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:21:01,585 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:21:01,588 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:21:01,589 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:21:01,592 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:21:01,595 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:21:01,597 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:21:01,604 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:21:01,612 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:21:01] "GET / HTTP/1.1" 500 -
2019-08-14 10:21:40,423 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:21:42,756 - router - INFO - Get all to-dos incomming request
2019-08-14 10:21:42,772 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:21:46,732 - python_app.repository - DEBUG - Getting session
2019-08-14 10:21:47,888 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:21:47,889 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:21:47,894 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:21:47,896 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:21:47,902 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:21:47,904 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:21:47,905 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:23:21,858 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:23:21,885 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:23:21] "GET / HTTP/1.1" 500 -
2019-08-14 10:23:47,899 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:24:01,374 - router - INFO - Get all to-dos incomming request
2019-08-14 10:24:01,406 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:24:04,686 - python_app.repository - DEBUG - Getting session
2019-08-14 10:24:06,321 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:24:06,323 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:24:06,326 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:24:06,329 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:24:06,333 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:24:06,337 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:24:06,338 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:24:12,855 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:24:12,875 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:24:12] "GET / HTTP/1.1" 500 -
2019-08-14 10:36:48,641 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:36:51,770 - router - INFO - Get all to-dos incomming request
2019-08-14 10:36:51,789 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:36:55,262 - python_app.repository - DEBUG - Getting session
2019-08-14 10:36:55,288 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:36:55,290 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:36:55,294 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:36:55,298 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:36:55,302 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:36:55,306 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:36:55,307 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:36:55,318 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:36:55,330 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:36:55] "GET / HTTP/1.1" 500 -
2019-08-14 10:37:00,429 - router - INFO - Get to-do incomming request
2019-08-14 10:37:00,431 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:37:00,433 - python_app.repository - DEBUG - Getting session
2019-08-14 10:37:00,438 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:37:00,439 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:37:00,442 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:37:00,443 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:37:00,445 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:37:00,447 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:37:00,448 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:37:00,453 - Python app - ERROR - Exception on /1 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 19, in get_todo
    return jsonify(handler.get_todo(todo_id))
  File "/home/user/python-training/python_app/handler.py", line 24, in get_todo
    for row in rows:
TypeError: 'Todo' object is not iterable
2019-08-14 10:37:00,459 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:37:00] "GET /1 HTTP/1.1" 500 -
2019-08-14 10:37:32,534 - sqlalchemy.pool.impl.NullPool - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140081432098560 and this is thread id 140081700534016.
2019-08-14 10:37:32,536 - sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <sqlite3.Connection object at 0x7f674c2b5490>
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140081432098560 and this is thread id 140081700534016.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140081432098560 and this is thread id 140081700534016.
2019-08-14 10:37:52,765 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:37:55,693 - router - INFO - Get to-do incomming request
2019-08-14 10:37:55,713 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:37:55,714 - python_app.repository - DEBUG - Getting session
2019-08-14 10:37:55,726 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:37:55,727 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:37:55,731 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:37:55,732 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:37:55,735 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:37:55,737 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:37:55,739 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:37:55,746 - Python app - ERROR - Exception on /1 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 19, in get_todo
    return jsonify(handler.get_todo(todo_id))
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Todo' is not JSON serializable
2019-08-14 10:37:55,757 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:37:55] "GET /1 HTTP/1.1" 500 -
2019-08-14 10:42:52,428 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:42:56,724 - router - INFO - Get to-do incomming request
2019-08-14 10:42:56,752 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:42:56,754 - python_app.repository - DEBUG - Getting session
2019-08-14 10:42:56,767 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:42:56,768 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:42:56,771 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:42:56,773 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:42:56,776 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:42:56,780 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:42:56,785 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:42:56,792 - Python app - ERROR - Exception on /1 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Todo.
2019-08-14 10:42:56,800 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:42:56] "GET /1 HTTP/1.1" 500 -
2019-08-14 10:43:08,754 - router - INFO - Get all to-dos incomming request
2019-08-14 10:43:08,756 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:43:13,001 - python_app.repository - DEBUG - Getting session
2019-08-14 10:43:13,012 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:13,015 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:13,019 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:13,020 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:13,022 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:43:13,024 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:43:13,026 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:13,032 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:43:13,036 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:43:13] "GET / HTTP/1.1" 500 -
2019-08-14 10:43:20,699 - router - INFO - Get all to-dos incomming request
2019-08-14 10:43:20,703 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:43:20,704 - python_app.repository - DEBUG - Getting session
2019-08-14 10:43:20,708 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:20,709 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:20,712 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:20,713 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:20,715 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:43:20,717 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:43:20,718 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:20,719 - Python app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2019-08-14 10:43:20,721 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:43:20] "GET / HTTP/1.1" 500 -
2019-08-14 10:43:23,626 - router - INFO - Get to-do incomming request
2019-08-14 10:43:23,628 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:43:23,629 - python_app.repository - DEBUG - Getting session
2019-08-14 10:43:23,633 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:23,635 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:23,638 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:23,639 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:23,642 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:43:23,645 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:43:23,648 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:43:23,652 - Python app - ERROR - Exception on /1 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Todo.
2019-08-14 10:43:23,655 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:43:23] "GET /1 HTTP/1.1" 500 -
2019-08-14 10:43:42,787 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:43:46,369 - router - INFO - Get to-do incomming request
2019-08-14 10:43:46,393 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:43:46,394 - python_app.repository - DEBUG - Getting session
2019-08-14 10:43:46,417 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:46,420 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:46,426 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:43:46,429 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:43:46,441 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:43:46,444 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:43:46,444 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:43:46,453 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:43:46] "GET /1 HTTP/1.1" 200 -
2019-08-14 10:44:02,268 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:44:05,624 - router - INFO - Get all to-dos incomming request
2019-08-14 10:44:05,637 - python_app.handler - INFO - Finding all to-dos
2019-08-14 10:44:05,638 - python_app.repository - DEBUG - Getting session
2019-08-14 10:44:05,648 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:44:05,650 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:44:05,652 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:44:05,654 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:44:05,657 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:44:05,660 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 10:44:05,664 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:44:05,678 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:44:05] "GET / HTTP/1.1" 200 -
2019-08-14 10:44:53,041 - router - INFO - Get to-do incomming request
2019-08-14 10:44:53,044 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:44:53,046 - python_app.repository - DEBUG - Getting session
2019-08-14 10:44:53,051 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:44:53,053 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:44:53,055 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:44:53,057 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:44:53,067 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:44:53,073 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
 LIMIT ? OFFSET ?
2019-08-14 10:44:53,076 - sqlalchemy.engine.base.Engine - INFO - (1, 0)
2019-08-14 10:44:53,082 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:44:53] "GET /1 HTTP/1.1" 200 -
2019-08-14 10:48:09,008 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:48:11,119 - router - INFO - Get to-do incomming request
2019-08-14 10:48:11,148 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:48:11,151 - python_app.repository - DEBUG - Getting session
2019-08-14 10:48:11,168 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:48:11,170 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:48:11,172 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:48:11,173 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:48:11,177 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:48:11,183 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 10:48:11,185 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 10:48:11,193 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:48:11] "GET /1 HTTP/1.1" 200 -
2019-08-14 10:59:30,235 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 10:59:35,929 - router - INFO - Get to-do incomming request
2019-08-14 10:59:35,955 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 10:59:35,956 - python_app.repository - DEBUG - Getting session
2019-08-14 10:59:35,969 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:59:35,970 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:59:35,971 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 10:59:35,973 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 10:59:35,975 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 10:59:35,979 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 10:59:35,980 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 10:59:35,990 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 10:59:35] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:47:10,120 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 11:47:12,801 - router - INFO - Get to-do incomming request
2019-08-14 11:47:12,824 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 11:47:12,825 - python_app.repository - DEBUG - Getting session
2019-08-14 11:47:12,841 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:47:12,844 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:47:12,848 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:47:12,849 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:47:12,854 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:47:12,861 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:47:12,862 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 11:47:12,865 - python_app.repository - INFO - Clossing session
2019-08-14 11:47:12,867 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:47:12,876 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:47:12] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:47:47,776 - router - INFO - Get to-do incomming request
2019-08-14 11:47:47,783 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 11:47:47,785 - python_app.repository - DEBUG - Getting session
2019-08-14 11:47:47,796 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:47:47,798 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:47:47,801 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:47:47,803 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:47:47,805 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:47:47,809 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:47:47,810 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 11:47:51,100 - python_app.repository - INFO - Clossing session
2019-08-14 11:47:52,082 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:48:05,706 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:48:05] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:51:40,319 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 11:51:42,287 - router - INFO - Get to-do incomming request
2019-08-14 11:51:42,315 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 11:51:42,317 - python_app.repository - DEBUG - Getting session
2019-08-14 11:51:42,336 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:51:42,337 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:51:42,345 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:51:42,349 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:51:42,353 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:51:42,357 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:51:42,359 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 11:51:46,050 - python_app.repository - INFO - Clossing session
2019-08-14 11:51:46,053 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:51:46,061 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:51:46] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:51:49,636 - router - INFO - Get to-do incomming request
2019-08-14 11:51:49,640 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 11:51:49,641 - python_app.repository - DEBUG - Getting session
2019-08-14 11:51:49,647 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:51:49,649 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:51:49,652 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:51:49,654 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:51:49,657 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:51:49,661 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:51:49,663 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 11:51:49,666 - python_app.repository - DEBUG - Rollbacking session
2019-08-14 11:51:49,668 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:51:49,672 - python_app.repository - INFO - Clossing session
2019-08-14 11:51:49,675 - Python app - ERROR - Exception on /12 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 19, in get_todo
    return jsonify(handler.get_todo(todo_id))
  File "/home/user/python-training/python_app/handler.py", line 21, in get_todo
    todo = session.query(Todo).filter(Todo.id == todo_id).one()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3295, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2019-08-14 11:51:49,691 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:51:49] "GET /12 HTTP/1.1" 500 -
2019-08-14 11:54:28,432 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 11:54:32,049 - router - INFO - Get to-do incomming request
2019-08-14 11:54:32,083 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 11:54:32,084 - python_app.repository - DEBUG - Getting session
2019-08-14 11:54:32,100 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:54:32,102 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:54:32,110 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:54:32,115 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:54:32,128 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:54:32,138 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:54:32,141 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 11:54:32,150 - python_app.repository - DEBUG - Rollbacking session
2019-08-14 11:54:32,151 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:54:32,158 - python_app.repository - INFO - Clossing session
2019-08-14 11:54:32,161 - Python app - ERROR - Exception on /12 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/python_app/handler.py", line 22, in get_todo
    todo = session.query(Todo).filter(Todo.id == todo_id).one()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3295, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 19, in get_todo
    return jsonify(handler.get_todo(todo_id))
  File "/home/user/python-training/python_app/handler.py", line 23, in get_todo
    except NoResultFound:
NameError: name 'NoResultFound' is not defined
2019-08-14 11:54:32,189 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:54:32] "GET /12 HTTP/1.1" 500 -
2019-08-14 11:57:26,959 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 11:57:30,347 - router - INFO - Get to-do incomming request
2019-08-14 11:57:30,365 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 11:57:30,367 - python_app.repository - DEBUG - Getting session
2019-08-14 11:57:30,380 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:30,381 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:30,386 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:30,391 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:30,395 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:57:30,400 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:57:30,402 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 11:57:30,408 - python_app.repository - INFO - Clossing session
2019-08-14 11:57:30,410 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:57:30,415 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:57:30] "GET /12 HTTP/1.1" 200 -
2019-08-14 11:57:36,991 - router - INFO - Get to-do incomming request
2019-08-14 11:57:36,993 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 11:57:36,994 - python_app.repository - DEBUG - Getting session
2019-08-14 11:57:36,997 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:36,998 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:37,000 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:37,001 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:37,003 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:57:37,005 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:57:37,006 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 11:57:37,010 - python_app.repository - INFO - Clossing session
2019-08-14 11:57:37,012 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:57:37,015 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:57:37] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:57:48,251 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 11:57:51,339 - router - INFO - Get to-do incomming request
2019-08-14 11:57:51,359 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 11:57:51,361 - python_app.repository - DEBUG - Getting session
2019-08-14 11:57:51,380 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:51,382 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:51,388 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:51,390 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:51,398 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:57:51,404 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:57:51,406 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 11:57:51,414 - python_app.repository - INFO - Clossing session
2019-08-14 11:57:51,416 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:57:51,422 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:57:51] "GET /1 HTTP/1.1" 200 -
2019-08-14 11:57:53,024 - router - INFO - Get to-do incomming request
2019-08-14 11:57:53,027 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 11:57:53,028 - python_app.repository - DEBUG - Getting session
2019-08-14 11:57:53,031 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:53,032 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:53,034 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 11:57:53,036 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 11:57:53,038 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 11:57:53,040 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 11:57:53,041 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 11:57:53,043 - python_app.repository - INFO - Clossing session
2019-08-14 11:57:53,044 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 11:57:53,048 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 11:57:53] "GET /12 HTTP/1.1" 200 -
2019-08-14 11:58:06,381 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 15:52:35,035 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 15:52:40,196 - router - INFO - Get to-do incomming request
2019-08-14 15:52:40,215 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 15:52:40,217 - python_app.repository - DEBUG - Getting session
2019-08-14 15:52:40,229 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:52:40,231 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:52:40,236 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:52:40,239 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:52:40,242 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 15:52:40,245 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 15:52:40,248 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 15:52:40,253 - python_app.repository - INFO - Clossing session
2019-08-14 15:52:40,255 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 15:52:40,257 - Python app - ERROR - Exception on /12 [GET]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 25, in get_todo
    if todo in None:
TypeError: argument of type 'NoneType' is not iterable
2019-08-14 15:52:40,266 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 15:52:40] "GET /12 HTTP/1.1" 500 -
2019-08-14 15:53:02,348 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 15:53:04,078 - router - INFO - Get to-do incomming request
2019-08-14 15:53:04,117 - python_app.handler - INFO - Finding todo with id 12
2019-08-14 15:53:04,120 - python_app.repository - DEBUG - Getting session
2019-08-14 15:53:04,138 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:04,140 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:04,144 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:04,146 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:04,153 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 15:53:04,158 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 15:53:04,159 - sqlalchemy.engine.base.Engine - INFO - ('12',)
2019-08-14 15:53:04,163 - python_app.repository - INFO - Clossing session
2019-08-14 15:53:04,167 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 15:53:04,172 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 15:53:04] "GET /12 HTTP/1.1" 404 -
2019-08-14 15:53:09,130 - router - INFO - Get to-do incomming request
2019-08-14 15:53:09,132 - python_app.handler - INFO - Finding todo with id 1
2019-08-14 15:53:09,133 - python_app.repository - DEBUG - Getting session
2019-08-14 15:53:09,138 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:09,139 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:09,142 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:09,143 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:09,145 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 15:53:09,146 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 15:53:09,148 - sqlalchemy.engine.base.Engine - INFO - ('1',)
2019-08-14 15:53:09,150 - python_app.repository - INFO - Clossing session
2019-08-14 15:53:09,151 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 15:53:09,156 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 15:53:09] "GET /1 HTTP/1.1" 200 -
2019-08-14 15:53:13,023 - router - INFO - Get all to-dos incomming request
2019-08-14 15:53:13,025 - python_app.handler - INFO - Finding all to-dos
2019-08-14 15:53:13,026 - python_app.repository - DEBUG - Getting session
2019-08-14 15:53:13,033 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:13,035 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:13,036 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 15:53:13,039 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:13,045 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 15:53:13,049 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 15:53:13,051 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 15:53:13,056 - python_app.repository - INFO - Clossing session
2019-08-14 15:53:13,058 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 15:53:13,062 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 15:53:13] "GET / HTTP/1.1" 200 -
2019-08-14 15:56:57,796 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 15:58:42,720 - router - INFO - Add to-do incomming request
2019-08-14 15:58:42,749 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 15:58:42,750 - python_app.repository - DEBUG - Getting session
2019-08-14 15:58:42,752 - python_app.handler - INFO - Adding new to-do
2019-08-14 15:58:42,753 - python_app.repository - DEBUG - Rollbacking session
2019-08-14 15:58:42,755 - python_app.repository - INFO - Clossing session
2019-08-14 15:58:42,758 - Python app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 43, in add_todo
    return handler.add_todo(todo_id, todo_description)
  File "/home/user/python-training/python_app/handler.py", line 33, in add_todo
    todo = Todo(todo_id, todo_description)
TypeError: __init__() takes 1 positional argument but 3 were given
2019-08-14 15:58:42,766 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 15:58:42] "POST / HTTP/1.1" 500 -
2019-08-14 16:01:08,852 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:01:12,384 - router - INFO - Add to-do incomming request
2019-08-14 16:01:12,401 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 16:01:12,402 - python_app.repository - DEBUG - Getting session
2019-08-14 16:01:12,403 - python_app.handler - INFO - Adding new to-do
2019-08-14 16:01:12,410 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:01:12,413 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:01:12,418 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:01:12,421 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:01:12,426 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:01:12,432 - sqlalchemy.engine.base.Engine - INFO - INSERT INTO todos (id, description) VALUES (?, ?)
2019-08-14 16:01:12,434 - sqlalchemy.engine.base.Engine - INFO - ('2', 'tomar mates')
2019-08-14 16:01:12,438 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 16:01:12,443 - python_app.repository - INFO - Clossing session
2019-08-14 16:01:12,446 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:01:12] "POST / HTTP/1.1" 200 -
2019-08-14 16:42:23,927 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:42:28,839 - router - INFO - Get all to-dos incomming request
2019-08-14 16:42:28,873 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:42:28,874 - python_app.repository - DEBUG - Getting session
2019-08-14 16:42:28,890 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:28,892 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:28,895 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:28,896 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:28,899 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:42:28,903 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:42:28,904 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:28,908 - python_app.repository - INFO - Clossing session
2019-08-14 16:42:28,910 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:42:28,916 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:42:28] "GET / HTTP/1.1" 200 -
2019-08-14 16:42:36,708 - router - INFO - Delete to-do incomming request
2019-08-14 16:42:36,712 - python_app.handler - INFO - Delete todo with id 2
2019-08-14 16:42:36,714 - python_app.repository - DEBUG - Getting session
2019-08-14 16:42:36,719 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:36,721 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:36,725 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:36,726 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:36,728 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:42:36,731 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:42:36,733 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 16:42:36,737 - python_app.repository - INFO - Clossing session
2019-08-14 16:42:36,739 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:42:36,743 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:42:36] "DELETE /2 HTTP/1.1" 200 -
2019-08-14 16:42:39,742 - router - INFO - Get all to-dos incomming request
2019-08-14 16:42:39,744 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:42:39,745 - python_app.repository - DEBUG - Getting session
2019-08-14 16:42:39,750 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:39,751 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:39,755 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:39,755 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:39,756 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:42:39,758 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:42:39,761 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:39,765 - python_app.repository - INFO - Clossing session
2019-08-14 16:42:39,767 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:42:39,771 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:42:39] "GET / HTTP/1.1" 200 -
2019-08-14 16:42:41,047 - router - INFO - Get all to-dos incomming request
2019-08-14 16:42:41,050 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:42:41,051 - python_app.repository - DEBUG - Getting session
2019-08-14 16:42:41,057 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:41,059 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:41,061 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:41,062 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:41,064 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:42:41,067 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:42:41,070 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:41,072 - python_app.repository - INFO - Clossing session
2019-08-14 16:42:41,074 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:42:41,078 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:42:41] "GET / HTTP/1.1" 200 -
2019-08-14 16:42:57,548 - router - INFO - Get all to-dos incomming request
2019-08-14 16:42:57,551 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:42:57,552 - python_app.repository - DEBUG - Getting session
2019-08-14 16:42:57,557 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:57,559 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:57,563 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:42:57,565 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:57,567 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:42:57,572 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:42:57,574 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:42:57,578 - python_app.repository - INFO - Clossing session
2019-08-14 16:42:57,579 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:42:57,582 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:42:57] "GET / HTTP/1.1" 200 -
2019-08-14 16:43:00,857 - router - INFO - Delete to-do incomming request
2019-08-14 16:43:00,859 - python_app.handler - INFO - Delete todo with id 2
2019-08-14 16:43:00,860 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:00,864 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:00,866 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:00,870 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:00,871 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:00,873 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:00,875 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:43:00,877 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 16:43:00,880 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:00,881 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:00,886 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:00] "DELETE /2 HTTP/1.1" 200 -
2019-08-14 16:43:02,821 - router - INFO - Get all to-dos incomming request
2019-08-14 16:43:02,824 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:43:02,824 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:02,828 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:02,830 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:02,833 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:02,834 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:02,837 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:02,841 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:43:02,844 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:02,847 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:02,848 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:02,854 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:02] "GET / HTTP/1.1" 200 -
2019-08-14 16:43:04,188 - router - INFO - Get all to-dos incomming request
2019-08-14 16:43:04,190 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:43:04,191 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:04,194 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:04,196 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:04,203 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:04,205 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:04,210 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:04,213 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:43:04,216 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:04,219 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:04,220 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:04,223 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:04] "GET / HTTP/1.1" 200 -
2019-08-14 16:43:10,468 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:43:12,070 - router - INFO - Delete to-do incomming request
2019-08-14 16:43:12,088 - python_app.handler - INFO - Delete todo with id 2
2019-08-14 16:43:12,090 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:12,100 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:12,103 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:12,107 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:12,110 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:12,116 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:12,120 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:43:12,122 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 16:43:12,133 - sqlalchemy.engine.base.Engine - INFO - DELETE FROM todos WHERE todos.id = ?
2019-08-14 16:43:12,134 - sqlalchemy.engine.base.Engine - INFO - (2,)
2019-08-14 16:43:12,137 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 16:43:12,143 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:12,147 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:12] "DELETE /2 HTTP/1.1" 200 -
2019-08-14 16:43:15,337 - router - INFO - Get all to-dos incomming request
2019-08-14 16:43:15,340 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:43:15,340 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:15,343 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:15,345 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:15,348 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:15,350 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:15,353 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:15,355 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:43:15,357 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:15,365 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:15,369 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:15,374 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:15] "GET / HTTP/1.1" 200 -
2019-08-14 16:43:21,755 - router - INFO - Add to-do incomming request
2019-08-14 16:43:21,759 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 16:43:21,760 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:21,762 - python_app.handler - INFO - Adding new to-do
2019-08-14 16:43:21,765 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:21,767 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:21,770 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:21,773 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:21,776 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:21,781 - sqlalchemy.engine.base.Engine - INFO - INSERT INTO todos (id, description) VALUES (?, ?)
2019-08-14 16:43:21,783 - sqlalchemy.engine.base.Engine - INFO - ('2', 'tomar mates')
2019-08-14 16:43:21,790 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 16:43:21,798 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:21,803 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:21] "POST / HTTP/1.1" 200 -
2019-08-14 16:43:24,128 - router - INFO - Get all to-dos incomming request
2019-08-14 16:43:24,131 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:43:24,131 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:24,135 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:24,137 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:24,141 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:24,142 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:24,144 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:24,147 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:43:24,148 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:24,151 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:24,153 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:24,155 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:24] "GET / HTTP/1.1" 200 -
2019-08-14 16:43:33,459 - router - INFO - Delete to-do incomming request
2019-08-14 16:43:33,462 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:43:33,463 - python_app.repository - DEBUG - Getting session
2019-08-14 16:43:33,466 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:33,468 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:33,470 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:43:33,472 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:43:33,475 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:43:33,478 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:43:33,482 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:43:33,487 - python_app.repository - DEBUG - Rollbacking session
2019-08-14 16:43:33,488 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:43:33,493 - python_app.repository - INFO - Clossing session
2019-08-14 16:43:33,497 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1979, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 34, in delete_todo
    return handler.delete_todo(todo_id)
  File "/home/user/python-training/python_app/handler.py", line 45, in delete_todo
    session.delete(todo)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1981, in delete
    raise exc.UnmappedInstanceError(instance)
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2019-08-14 16:43:33,504 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:43:33] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:45:58,036 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:45:59,696 - router - INFO - Delete to-do incomming request
2019-08-14 16:45:59,725 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:45:59,728 - python_app.repository - DEBUG - Getting session
2019-08-14 16:45:59,742 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:45:59,744 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:45:59,749 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:45:59,750 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:45:59,754 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:45:59,758 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:45:59,761 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:45:59,767 - python_app.repository - INFO - Clossing session
2019-08-14 16:45:59,769 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:45:59,771 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:45:59,780 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:45:59] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:46:07,169 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:46:10,104 - router - INFO - Delete to-do incomming request
2019-08-14 16:46:10,144 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:46:10,147 - python_app.repository - DEBUG - Getting session
2019-08-14 16:46:10,166 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:46:10,169 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:46:10,172 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:46:10,175 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:46:10,182 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:46:10,186 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:46:10,187 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:46:10,192 - python_app.repository - INFO - Clossing session
2019-08-14 16:46:10,193 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:46:10,197 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:46:10,207 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:46:10] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:47:33,405 - router - INFO - Delete to-do incomming request
2019-08-14 16:47:33,412 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:47:33,414 - python_app.repository - DEBUG - Getting session
2019-08-14 16:47:33,420 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:33,422 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:33,424 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:33,426 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:33,429 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:47:33,432 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:47:33,433 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:47:33,438 - python_app.repository - INFO - Clossing session
2019-08-14 16:47:33,439 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:47:33,441 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:47:33,443 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:47:33] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:47:36,193 - router - INFO - Delete to-do incomming request
2019-08-14 16:47:36,196 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:47:36,197 - python_app.repository - DEBUG - Getting session
2019-08-14 16:47:36,200 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:36,202 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:36,204 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:36,205 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:36,207 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:47:36,210 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:47:36,212 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:47:36,214 - python_app.repository - INFO - Clossing session
2019-08-14 16:47:36,215 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:47:36,225 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:47:36,232 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:47:36] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:47:42,790 - router - INFO - Delete to-do incomming request
2019-08-14 16:47:42,793 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:47:42,794 - python_app.repository - DEBUG - Getting session
2019-08-14 16:47:44,636 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:44,638 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:44,642 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:47:44,645 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:47:44,648 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:47:44,652 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:47:44,655 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:53:45,630 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:53:48,608 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:53:55,506 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:53:59,316 - router - INFO - Delete to-do incomming request
2019-08-14 16:53:59,335 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:53:59,338 - python_app.repository - DEBUG - Getting session
2019-08-14 16:54:03,248 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:03,251 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:03,256 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:03,258 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:03,262 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:54:03,267 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:54:03,269 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:54:03,274 - python_app.repository - INFO - Clossing session
2019-08-14 16:54:03,276 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:54:03,279 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:54:03,286 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:54:03] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:54:25,607 - router - INFO - Delete to-do incomming request
2019-08-14 16:54:25,611 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:54:25,612 - python_app.repository - DEBUG - Getting session
2019-08-14 16:54:28,593 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:28,598 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:28,603 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:28,604 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:28,606 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:54:28,609 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:54:28,611 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:54:47,508 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:54:55,302 - router - INFO - Delete to-do incomming request
2019-08-14 16:54:55,330 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:54:55,334 - python_app.repository - DEBUG - Getting session
2019-08-14 16:54:58,623 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:58,626 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:58,630 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:54:58,631 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:54:58,636 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:54:58,640 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:54:58,642 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:54:58,646 - python_app.repository - INFO - Clossing session
2019-08-14 16:54:58,647 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:54:58,650 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:54:58,658 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:54:58] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:55:08,684 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:55:13,767 - router - INFO - Delete to-do incomming request
2019-08-14 16:55:13,800 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:55:13,802 - python_app.repository - DEBUG - Getting session
2019-08-14 16:55:20,626 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:55:20,627 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:55:20,633 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:55:20,636 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:55:20,641 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:55:20,645 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:55:20,646 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:55:24,238 - python_app.repository - INFO - Clossing session
2019-08-14 16:55:24,244 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:55:24,254 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:55:24,266 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:55:24] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:56:09,665 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:56:11,941 - router - INFO - Delete to-do incomming request
2019-08-14 16:56:11,968 - python_app.handler - INFO - Delete todo with id 27
2019-08-14 16:56:11,970 - python_app.repository - DEBUG - Getting session
2019-08-14 16:56:15,068 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:56:15,071 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:56:15,074 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:56:15,076 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:56:15,079 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:56:15,083 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:56:15,085 - sqlalchemy.engine.base.Engine - INFO - ('27',)
2019-08-14 16:56:15,089 - python_app.repository - INFO - Clossing session
2019-08-14 16:56:15,090 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:56:15,093 - Python app - ERROR - Exception on /27 [DELETE]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-08-14 16:56:15,099 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:56:15] "DELETE /27 HTTP/1.1" 500 -
2019-08-14 16:56:33,802 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 16:58:46,686 - router - INFO - Delete to-do incomming request
2019-08-14 16:58:46,703 - python_app.handler - INFO - Delete todo with id 7
2019-08-14 16:58:46,705 - python_app.repository - DEBUG - Getting session
2019-08-14 16:58:48,707 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:58:48,709 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:58:48,711 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:58:48,712 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:58:48,719 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:58:48,723 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:58:48,725 - sqlalchemy.engine.base.Engine - INFO - ('7',)
2019-08-14 16:58:48,728 - python_app.repository - INFO - Clossing session
2019-08-14 16:58:48,728 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:58:48,733 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:58:48] "DELETE /7 HTTP/1.1" 200 -
2019-08-14 16:59:00,527 - router - INFO - Delete to-do incomming request
2019-08-14 16:59:00,530 - python_app.handler - INFO - Delete todo with id 2
2019-08-14 16:59:00,531 - python_app.repository - DEBUG - Getting session
2019-08-14 16:59:02,713 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:59:02,716 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:59:02,721 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:59:02,723 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:59:02,725 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:59:02,729 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 16:59:02,733 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 16:59:02,741 - sqlalchemy.engine.base.Engine - INFO - DELETE FROM todos WHERE todos.id = ?
2019-08-14 16:59:02,742 - sqlalchemy.engine.base.Engine - INFO - (2,)
2019-08-14 16:59:02,743 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 16:59:02,754 - python_app.repository - INFO - Clossing session
2019-08-14 16:59:02,756 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:59:02] "DELETE /2 HTTP/1.1" 200 -
2019-08-14 16:59:05,523 - router - INFO - Get all to-dos incomming request
2019-08-14 16:59:05,526 - python_app.handler - INFO - Finding all to-dos
2019-08-14 16:59:05,527 - python_app.repository - DEBUG - Getting session
2019-08-14 16:59:05,532 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:59:05,535 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:59:05,537 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 16:59:05,538 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:59:05,541 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 16:59:05,543 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 16:59:05,544 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 16:59:05,546 - python_app.repository - INFO - Clossing session
2019-08-14 16:59:05,548 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 16:59:05,552 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 16:59:05] "GET / HTTP/1.1" 200 -
2019-08-14 17:02:52,042 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 17:02:57,722 - router - INFO - Add to-do incomming request
2019-08-14 17:02:57,739 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 17:02:57,741 - python_app.repository - DEBUG - Getting session
2019-08-14 17:02:57,743 - python_app.handler - INFO - Adding new to-do
2019-08-14 17:03:10,976 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 17:04:18,548 - router - INFO - Get all to-dos incomming request
2019-08-14 17:04:18,566 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:04:18,568 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:18,582 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:18,583 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:18,588 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:18,590 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:18,598 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:18,602 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:04:18,604 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:18,610 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:18,612 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:04:18,617 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:18] "GET / HTTP/1.1" 200 -
2019-08-14 17:04:21,083 - router - INFO - Add to-do incomming request
2019-08-14 17:04:21,087 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 17:04:21,087 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:21,089 - python_app.handler - INFO - Adding new to-do
2019-08-14 17:04:22,963 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:22,966 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:22,968 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:22,970 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:22,972 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:22,977 - sqlalchemy.engine.base.Engine - INFO - INSERT INTO todos (id, description) VALUES (?, ?)
2019-08-14 17:04:22,978 - sqlalchemy.engine.base.Engine - INFO - ('2', 'tomar mates')
2019-08-14 17:04:22,984 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 17:04:22,995 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:22,998 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:22] "POST / HTTP/1.1" 200 -
2019-08-14 17:04:25,734 - router - INFO - Get all to-dos incomming request
2019-08-14 17:04:25,736 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:04:25,737 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:25,739 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:25,741 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:25,743 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:25,745 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:25,749 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:25,754 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:04:25,756 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:25,759 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:25,762 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:04:25,766 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:25] "GET / HTTP/1.1" 200 -
2019-08-14 17:04:32,715 - router - INFO - Delete to-do incomming request
2019-08-14 17:04:32,718 - python_app.handler - INFO - Delete todo with id 9
2019-08-14 17:04:32,720 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:35,215 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:35,219 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:35,226 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:35,227 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:35,230 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:35,233 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 17:04:35,236 - sqlalchemy.engine.base.Engine - INFO - ('9',)
2019-08-14 17:04:35,238 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:35,239 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:04:35,242 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:35] "DELETE /9 HTTP/1.1" 404 -
2019-08-14 17:04:40,997 - router - INFO - Delete to-do incomming request
2019-08-14 17:04:41,000 - python_app.handler - INFO - Delete todo with id 2
2019-08-14 17:04:41,001 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:43,003 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:43,005 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:43,009 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:43,012 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:43,015 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:43,017 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 17:04:43,018 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 17:04:43,022 - sqlalchemy.engine.base.Engine - INFO - DELETE FROM todos WHERE todos.id = ?
2019-08-14 17:04:43,023 - sqlalchemy.engine.base.Engine - INFO - (2,)
2019-08-14 17:04:43,025 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 17:04:43,034 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:43,035 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:43] "DELETE /2 HTTP/1.1" 200 -
2019-08-14 17:04:46,415 - router - INFO - Get all to-dos incomming request
2019-08-14 17:04:46,418 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:04:46,419 - python_app.repository - DEBUG - Getting session
2019-08-14 17:04:46,423 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:46,424 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:46,428 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:04:46,431 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:46,435 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:04:46,439 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:04:46,441 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:04:46,445 - python_app.repository - INFO - Clossing session
2019-08-14 17:04:46,447 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:04:46,452 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:04:46] "GET / HTTP/1.1" 200 -
2019-08-14 17:08:31,002 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 17:08:42,974 - router - INFO - Get all to-dos incomming request
2019-08-14 17:08:42,993 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:08:42,994 - python_app.repository - DEBUG - Getting session
2019-08-14 17:08:43,006 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:43,009 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:43,014 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:43,016 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:43,023 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:08:43,033 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:08:43,055 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:43,066 - python_app.repository - INFO - Clossing session
2019-08-14 17:08:43,070 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:08:43,077 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:08:43] "GET / HTTP/1.1" 200 -
2019-08-14 17:08:46,493 - router - INFO - Add to-do incomming request
2019-08-14 17:08:46,497 - python_app.handler - INFO - Adding new TODO 2:tomar mates
2019-08-14 17:08:46,498 - python_app.repository - DEBUG - Getting session
2019-08-14 17:08:46,500 - python_app.handler - INFO - Adding new to-do
2019-08-14 17:08:53,172 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:53,174 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:53,178 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:53,180 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:53,183 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:08:53,188 - sqlalchemy.engine.base.Engine - INFO - INSERT INTO todos (id, description) VALUES (?, ?)
2019-08-14 17:08:53,189 - sqlalchemy.engine.base.Engine - INFO - ('2', 'tomar mates')
2019-08-14 17:08:53,193 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 17:08:53,205 - python_app.repository - INFO - Clossing session
2019-08-14 17:08:53,207 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:08:53] "POST / HTTP/1.1" 200 -
2019-08-14 17:08:56,476 - router - INFO - Get all to-dos incomming request
2019-08-14 17:08:56,479 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:08:56,480 - python_app.repository - DEBUG - Getting session
2019-08-14 17:08:56,484 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:56,486 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:56,491 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:08:56,492 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:56,496 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:08:56,498 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:08:56,500 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:08:56,508 - python_app.repository - INFO - Clossing session
2019-08-14 17:08:56,513 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:08:56,516 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:08:56] "GET / HTTP/1.1" 200 -
2019-08-14 17:08:59,702 - router - INFO - Update to-do incomming request
2019-08-14 17:09:04,305 - python_app.handler - INFO - Update TODO 2
2019-08-14 17:09:04,310 - python_app.repository - DEBUG - Getting session
2019-08-14 17:09:04,318 - python_app.handler - INFO - Finding to-do
2019-08-14 17:09:04,326 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:09:04,329 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:09:04,334 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:09:04,336 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:09:04,338 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:09:04,340 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 17:09:04,342 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 17:09:04,352 - python_app.handler - INFO - Updating to-do
2019-08-14 17:09:04,354 - python_app.repository - DEBUG - Rollbacking session
2019-08-14 17:09:04,355 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:09:04,357 - python_app.repository - INFO - Clossing session
2019-08-14 17:09:04,359 - Python app - ERROR - Exception on /2 [PUT]
Traceback (most recent call last):
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python-training/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python-training/router.py", line 54, in update_todo
    return handler.update_todo(todo_id, todo_description)
  File "/home/user/python-training/python_app/handler.py", line 65, in update_todo
    session.Update(todo)
AttributeError: 'Session' object has no attribute 'Update'
2019-08-14 17:09:04,367 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:09:04] "PUT /2 HTTP/1.1" 500 -
2019-08-14 17:11:08,845 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 17:11:17,013 - router - INFO - Update to-do incomming request
2019-08-14 17:11:17,036 - python_app.handler - INFO - Update TODO 2
2019-08-14 17:11:17,037 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:17,039 - python_app.handler - INFO - Finding to-do
2019-08-14 17:11:17,048 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:17,049 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:17,052 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:17,054 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:17,059 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:17,066 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 17:11:17,067 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 17:11:17,076 - python_app.handler - INFO - Updating to-do
2019-08-14 17:11:17,079 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 17:11:17,081 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:17,086 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:17] "PUT /2 HTTP/1.1" 200 -
2019-08-14 17:11:20,727 - router - INFO - Get all to-dos incomming request
2019-08-14 17:11:20,730 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:11:20,730 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:20,733 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:20,735 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:20,738 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:20,740 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:20,742 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:20,745 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:11:20,747 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:20,750 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:20,751 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:11:20,760 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:20] "GET / HTTP/1.1" 200 -
2019-08-14 17:11:23,684 - router - INFO - Get all to-dos incomming request
2019-08-14 17:11:23,687 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:11:23,688 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:23,692 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:23,694 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:23,698 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:23,699 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:23,702 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:23,708 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:11:23,710 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:23,714 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:23,716 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:11:23,721 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:23] "GET / HTTP/1.1" 200 -
2019-08-14 17:11:35,408 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-08-14 17:11:38,128 - router - INFO - Get all to-dos incomming request
2019-08-14 17:11:38,156 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:11:38,158 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:38,173 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:38,176 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:38,181 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:38,184 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:38,189 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:38,193 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:11:38,194 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:38,199 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:38,200 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:11:38,205 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:38] "GET / HTTP/1.1" 200 -
2019-08-14 17:11:42,712 - router - INFO - Update to-do incomming request
2019-08-14 17:11:42,715 - python_app.handler - INFO - Update TODO 2
2019-08-14 17:11:42,716 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:42,717 - python_app.handler - INFO - Finding to-do
2019-08-14 17:11:42,723 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:42,724 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:42,727 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:42,728 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:42,730 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:42,732 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos 
WHERE todos.id = ?
2019-08-14 17:11:42,733 - sqlalchemy.engine.base.Engine - INFO - ('2',)
2019-08-14 17:11:42,735 - python_app.handler - INFO - Updating to-do
2019-08-14 17:11:42,743 - sqlalchemy.engine.base.Engine - INFO - UPDATE todos SET description=? WHERE todos.id = ?
2019-08-14 17:11:42,746 - sqlalchemy.engine.base.Engine - INFO - ('pasear perro', 2)
2019-08-14 17:11:42,750 - sqlalchemy.engine.base.Engine - INFO - COMMIT
2019-08-14 17:11:42,761 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:42,763 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:42] "PUT /2 HTTP/1.1" 200 -
2019-08-14 17:11:47,821 - router - INFO - Get all to-dos incomming request
2019-08-14 17:11:47,825 - python_app.handler - INFO - Finding all to-dos
2019-08-14 17:11:47,827 - python_app.repository - DEBUG - Getting session
2019-08-14 17:11:47,832 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:47,835 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:47,840 - sqlalchemy.engine.base.Engine - INFO - SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-08-14 17:11:47,843 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:47,846 - sqlalchemy.engine.base.Engine - INFO - BEGIN (implicit)
2019-08-14 17:11:47,849 - sqlalchemy.engine.base.Engine - INFO - SELECT todos.id AS todos_id, todos.description AS todos_description 
FROM todos
2019-08-14 17:11:47,852 - sqlalchemy.engine.base.Engine - INFO - ()
2019-08-14 17:11:47,857 - python_app.repository - INFO - Clossing session
2019-08-14 17:11:47,859 - sqlalchemy.engine.base.Engine - INFO - ROLLBACK
2019-08-14 17:11:47,868 - werkzeug - INFO - 127.0.0.1 - - [14/Aug/2019 17:11:47] "GET / HTTP/1.1" 200 -
